# =========================
# DATABASE CONFIGURATION
# =========================
spring.datasource.url=jdbc:postgresql://db.sygqxmtuizftdyrdkxhf.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=DSS@301_IS1804
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Boot port
server.port=8081

# MONGODB CONFIGURATION
# =========================
spring.data.mongodb.uri=mongodb+srv://User:123@clusterdss.sm6n3tm.mongodb.net/DSS301?retryWrites=true&w=majority&appName=ClusterDSS