# =========================
# DATABASE CONFIGURATION
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/dss301
spring.datasource.username=postgres
spring.datasource.password=Hinh123@
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Boot port
server.port=8081

# MONGODB CONFIGURATION
# =========================
spring.data.mongodb.uri=mongodb+srv://hinhtxhe172549:iw6fuoPlI3Nvrr38@cluster0.67kzgez.mongodb.net/DSS301?retryWrites=true&w=majority&appName=Cluster0