# =========================
# DATABASE CONFIGURATION
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/Dss301
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Boot port
server.port=8081

# MONGODB CONFIGURATION
# =========================
spring.data.mongodb.uri=mongodb+srv://locchac5:123@clusterdss.sm6n3tm.mongodb.net/DSS301?appName=ClusterDSS